In [2]:
import numpy as np

## Scalars

In [2]:
s = np.array(5)

In [3]:
s

array(5)

In [4]:
type(s)

numpy.ndarray

In [5]:
s.shape

()

In [6]:
s.dtype

dtype('int64')

In [7]:
x = s+3

In [8]:
x

8

In [9]:
x.shape

()

In [10]:
x.dtype

dtype('int64')

## Vector

In [11]:
v = np.array([1,2,3])

Size of tuple with shape represents the dimensions of the data.  

scalars &nbsp; &nbsp; &nbsp;&nbsp;  : 0 dimension  
vector &nbsp; &nbsp; &nbsp; &nbsp;  : 1 dimension  
matrices &nbsp;&nbsp;&nbsp;&nbsp;: 2 dimension  
tensor &nbsp; &nbsp; &nbsp; &nbsp;  : 2+ dimensions  


In [12]:
v.shape

(3,)

In [13]:
v.dtype

dtype('int64')

## Matrices

In [16]:
m = np.array([[1,2,3], [4,5,6]])

Each list represents a row

In [17]:
m.shape

(2, 3)

## Tensors

In [18]:
t = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [19]:
t.shape

(3, 2, 3)

## Reshape

In [20]:
v

array([1, 2, 3])

In [21]:
v.shape

(3,)

In [22]:
v_m = v.reshape(1,3)

In [23]:
v_m

array([[1, 2, 3]])

In [24]:
v_m.shape

(1, 3)

In [26]:
v_m2 = v.reshape(3,1)

In [27]:
v_m2

array([[1],
       [2],
       [3]])

In [28]:
v_m2.shape

(3, 1)

In [29]:
v_m3 = v[:]

In [30]:
v_m3.shape

(3,)

In [31]:
v_m3 = v[None, :]

In [32]:
v_m3.shape

(1, 3)

In [33]:
v_m4 = v[:, None]

In [34]:
v_m4.shape

(3, 1)

???

# Matrix multiplication

In [6]:
m = np.array([[1,2,3],[4,5,6]])

In [7]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
m.shape

(2, 3)

In [5]:
n = m*0.25
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [9]:
n.shape

(2, 3)

In [13]:
m*n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

Element wise : * , np.matmul()

In [12]:
np.multiply(m, n)

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

### matrix product 

In [14]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
a.shape

(2, 4)

In [16]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [17]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
b.shape

(4, 3)

In [ ]:
%pdb
c = a* b

Automatic pdb calling has been turned ON


ValueError: operands could not be broadcast together with shapes (2,4) (4,3) 

> <ipython-input-31-03f9cf627644>(2)<module>()
      1 get_ipython().run_line_magic('pdb', '')
----> 2 c = a* b



ipdb>  print (a)


[[1 2 3 4]
 [5 6 7 8]]


ipdb>  print (b)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


ipdb>  print (a.shape)


(2, 4)


ipdb>  print (b.shape)


(4, 3)


ipdb>  help(*)


*** No help for '(*)'


In [20]:
c = a @ b

In [21]:
c.shape

(2, 3)

In [22]:
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [23]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [24]:
c.shape

(2, 3)

In [25]:
c = np.dot(a, b)

In [26]:
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [27]:
c.shape

(2, 3)

## Matrix Transpose

In [3]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
m.shape

(3, 4)

In [5]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [6]:
m.T.shape

(4, 3)

shared memory or m and m.T

In [7]:
m_t = m.T
m_t[3][1] = 200
m_t
# displays the following result:
# array([[ 1,   5, 9],
#        [ 2,   6, 10],
#        [ 3,   7, 11],
#        [ 4, 200, 12]])

m
# displays the following result:
# array([[ 1,  2,  3,   4],
#        [ 5,  6,  7, 200],
#        [ 9, 10, 11,  12]])


array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

In [8]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [9]:
inputs.shape

(1, 4)

In [10]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [11]:
weights.shape

(3, 4)

In [12]:
inputs @ weights

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [16]:
a = inputs @ weights.T
a

array([[-0.01299,  0.00664,  0.13494]])

In [17]:
a.shape

(1, 3)

In [18]:
weights @ inputs.T

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])