In [1]:
import numpy as np

## Scalars

In [2]:
s = np.array(5)

In [3]:
s

array(5)

In [4]:
type(s)

numpy.ndarray

In [5]:
s.shape

()

In [6]:
s.dtype

dtype('int64')

In [7]:
x = s+3

In [8]:
x

8

In [9]:
x.shape

()

In [10]:
x.dtype

dtype('int64')

## Vector

In [11]:
v = np.array([1,2,3])

Size of tuple with shape represents the dimensions of the data.  

scalars &nbsp; &nbsp; &nbsp;&nbsp;  : 0 dimension  
vector &nbsp; &nbsp; &nbsp; &nbsp;  : 1 dimension  
matrices &nbsp;&nbsp;&nbsp;&nbsp;: 2 dimension  
tensor &nbsp; &nbsp; &nbsp; &nbsp;  : 2+ dimensions  


In [12]:
v.shape

(3,)

In [13]:
v.dtype

dtype('int64')

## Matrices

In [16]:
m = np.array([[1,2,3], [4,5,6]])

Each list represents a row

In [17]:
m.shape

(2, 3)

## Tensors

In [18]:
t = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [19]:
t.shape

(3, 2, 3)

## Reshape

In [20]:
v

array([1, 2, 3])

In [21]:
v.shape

(3,)

In [22]:
v_m = v.reshape(1,3)

In [23]:
v_m

array([[1, 2, 3]])

In [24]:
v_m.shape

(1, 3)

In [26]:
v_m2 = v.reshape(3,1)

In [27]:
v_m2

array([[1],
       [2],
       [3]])

In [28]:
v_m2.shape

(3, 1)

In [29]:
v_m3 = v[:]

In [30]:
v_m3.shape

(3,)

In [31]:
v_m3 = v[None, :]

In [32]:
v_m3.shape

(1, 3)

In [33]:
v_m4 = v[:, None]

In [34]:
v_m4.shape

(3, 1)

???